### ISSUE TITLE
ETS更新了，全局界面已换成蓝色，软件里的图片也该改一改了

### ISSUE THREAD

**Issue by GaoYuan522** [XYCode-Kerman/FuckETS#1]

**Comment by XYCode-Kerman** [comment]
旧版本也是兼容的，我这边测试v5.6.3正常。
最近在忙中考，没太多时间维护了，见谅

**Comment by GaoYuan522** [comment]
> 旧版本也是兼容的，我这边测试v5.6.3正常。
> 最近在忙中考，没太多时间维护了，见谅

真是人外有人，山外有山，天外有天啊，加油！祝金榜题名！

**Comment by XYCode-Kerman** [comment]
> > 旧版本也是兼容的，我这边测试v5.6.3正常。
> > 最近在忙中考，没太多时间维护了，见谅
> 
> 真是人外有人，山外有山，天外有天啊，加油！祝金榜题名！

谢谢鼓励！
